"""bigint counters, nullable capacity, monitoring_disabled flag

Revision ID: 259ebaf4072a
Revises: b7df42a4f90d
Create Date: 2026-09-01 15:46:43.756298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259ebaf4072a'
down_revision: Union[str, None] = 'b7df42a4f90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.alter_column('rx_bytes_delta',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('tx_bytes_delta',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('poll_states', schema=None) as batch_op:
        batch_op.alter_column('last_in_octets',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('last_out_octets',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('snmp_interfaces', schema=None) as batch_op:
        batch_op.alter_column('speed_bps',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('wan_links', schema=None) as batch_op:
        # server_default backfills existing rows (none of them were
        # "intentionally disabled" before this flag existed); the app-level
        # default (models.py) takes over for new rows going forward.
        batch_op.add_column(sa.Column('monitoring_disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('circuit_capacity_bps',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wan_links', schema=None) as batch_op:
        batch_op.alter_column('circuit_capacity_bps',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('monitoring_disabled')

    with op.batch_alter_table('snmp_interfaces', schema=None) as batch_op:
        batch_op.alter_column('speed_bps',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('poll_states', schema=None) as batch_op:
        batch_op.alter_column('last_out_octets',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('last_in_octets',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.alter_column('tx_bytes_delta',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('rx_bytes_delta',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
