"""add system settings and per-link polling interval overrides

Revision ID: b7df42a4f90d
Revises: e19d0438af45
Create Date: 2026-08-17 15:47:35.045716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7df42a4f90d'
down_revision: Union[str, None] = 'e19d0438af45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icmp_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('snmp_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('wan_links', sa.Column('icmp_interval_seconds', sa.Integer(), nullable=True))
    op.add_column('wan_links', sa.Column('snmp_interval_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wan_links', 'snmp_interval_seconds')
    op.drop_column('wan_links', 'icmp_interval_seconds')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
