"""initial schema

Revision ID: e19d0438af45
Revises: 
Create Date: 2026-08-17 09:15:54.175002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19d0438af45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('primary_contact', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('isps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('badge_key', sa.String(length=50), nullable=False),
    sa.Column('support_phone', sa.String(length=50), nullable=True),
    sa.Column('noc_email', sa.String(length=200), nullable=True),
    sa.Column('portal_url', sa.String(length=500), nullable=True),
    sa.Column('escalation_contact', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('snmp_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Enum('v2c', 'v3', name='snmpversion'), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'engineer', 'viewer', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', name='uq_city_customer_name')
    )
    op.create_table('suburbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'name', name='uq_suburb_city_name')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('suburb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('primary_contact', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['suburb_id'], ['suburbs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wan_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.Column('name_generated', sa.String(length=500), nullable=False),
    sa.Column('circuit_capacity_bps', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'backup', 'failover', 'load_balanced', name='wanrole'), nullable=False),
    sa.Column('public_ip', sa.String(length=100), nullable=True),
    sa.Column('device_vendor', sa.String(length=100), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('icmp_enabled', sa.Boolean(), nullable=False),
    sa.Column('icmp_target_ip', sa.String(length=100), nullable=True),
    sa.Column('snmp_enabled', sa.Boolean(), nullable=False),
    sa.Column('snmp_target_ip', sa.String(length=100), nullable=True),
    sa.Column('snmp_version', sa.Enum('v2c', 'v3', name='snmpversion'), nullable=True),
    sa.Column('snmp_credential_id', sa.Integer(), nullable=True),
    sa.Column('selected_if_index', sa.Integer(), nullable=True),
    sa.Column('selected_interface_name', sa.String(length=200), nullable=True),
    sa.Column('selected_interface_ip', sa.String(length=100), nullable=True),
    sa.Column('selected_interface_alias', sa.String(length=200), nullable=True),
    sa.Column('monitoring_status', sa.Enum('fully_monitored', 'icmp_only', 'snmp_only', 'monitoring_disabled', 'not_configured', name='monitoringstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sustained_util_threshold_percent', sa.Float(), nullable=False),
    sa.Column('sustained_util_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.ForeignKeyConstraint(['snmp_credential_id'], ['snmp_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wan_link_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('wan_down', 'wan_recovered', 'high_latency', 'packet_loss', 'sustained_utilisation', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alertseverity'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wan_link_id'], ['wan_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_wan_link_id'), 'alerts', ['wan_link_id'], unique=False)
    op.create_table('engineer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wan_link_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wan_link_id'], ['wan_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wan_link_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rx_bps', sa.Float(), nullable=True),
    sa.Column('tx_bps', sa.Float(), nullable=True),
    sa.Column('total_bps', sa.Float(), nullable=True),
    sa.Column('utilisation_percent', sa.Float(), nullable=True),
    sa.Column('rx_bytes_delta', sa.Integer(), nullable=True),
    sa.Column('tx_bytes_delta', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss_percent', sa.Float(), nullable=True),
    sa.Column('jitter_ms', sa.Float(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['wan_link_id'], ['wan_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_timestamp'), 'measurements', ['timestamp'], unique=False)
    op.create_index(op.f('ix_measurements_wan_link_id'), 'measurements', ['wan_link_id'], unique=False)
    op.create_table('poll_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wan_link_id', sa.Integer(), nullable=False),
    sa.Column('last_snmp_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_in_octets', sa.Integer(), nullable=True),
    sa.Column('last_out_octets', sa.Integer(), nullable=True),
    sa.Column('last_icmp_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('utilisation_breach_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_down', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['wan_link_id'], ['wan_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wan_link_id')
    )
    op.create_table('snmp_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wan_link_id', sa.Integer(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('alias', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('speed_bps', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('admin_status', sa.String(length=20), nullable=True),
    sa.Column('oper_status', sa.String(length=20), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wan_link_id'], ['wan_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wan_link_id', 'if_index', name='uq_interface_wan_ifindex')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snmp_interfaces')
    op.drop_table('poll_states')
    op.drop_index(op.f('ix_measurements_wan_link_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('engineer_notes')
    op.drop_index(op.f('ix_alerts_wan_link_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('wan_links')
    op.drop_table('branches')
    op.drop_table('suburbs')
    op.drop_table('cities')
    op.drop_table('users')
    op.drop_table('snmp_credentials')
    op.drop_table('isps')
    op.drop_table('customers')
    # ### end Alembic commands ###
